# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_taggable}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wilker L\303\272cio", "Kris Kowalik"]
  s.date = %q{2010-07-19}
  s.description = %q{Mongoid Taggable provides some helpers to create taggable documents.}
  s.email = %q{wilkerlucio@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "README.textile",
     "Rakefile",
     "init.rb",
     "install.rb",
     "lib/mongoid/taggable.rb",
     "rails/init.rb",
     "spec/mongoid/taggable_spec.rb",
     "spec/spec_helper.rb",
     "tasks/mongoid_taggable_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/kriss/mongo_taggable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mongoid taggable behaviour}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/mongoid/taggable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

